assistant/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/web/')),
    path('web/', include('web.urls')),  
    path('accounts/', include('django.contrib.auth.urls')),  
]

web/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.DiaryListView.as_view()),
    path('diary/create/', views.DiaryCreate.as_view()),  
    path('diary/<int:pk>/update/', views.DiaryUpdate.as_view()),
    path('diary/<int:pk>/delete/', views.DiaryDelete.as_view()), 
    path('money', views.MoneyListView.as_view()),
    path('money/create/', views.MoneyCreate.as_view()),
    path('money/<int:pk>/update/', views.MoneyUpdate.as_view()),
    path('money/<int:pk>/delete/', views.MoneyDelete.as_view()),    
]

web/models.py
# -*- coding: UTF-8 -*-
from django.db import models

# 日誌
class Diary(models.Model):
    memo = models.TextField(verbose_name='內容')
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.memo
      
# 帳目
class Money(models.Model):
    CHOICES = (
      (1, "飲食"),
      (2, "衣服"),
      (3, "交通"),
      (4, "教育"),
      (5, "娛樂"),
      (6, "其它"),
    )    
    item = models.CharField(max_length=30, verbose_name='項目')
    kind = models.IntegerField(default=0, choices=CHOICES, verbose_name='類別')
    price = models.IntegerField(default=0, verbose_name='金額')
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.item

web/forms.py
from django import forms
from .models import Diary, Money

class DiaryForm(forms.ModelForm):
  class Meta:
    model = Diary
    fields = ['memo']
    widgets = {
      'memo': forms.Textarea(attrs={'class': 'form-control'}),
    }

class MoneyForm(forms.ModelForm):
  class Meta:
    model = Money
    fields = '__all__'
    widgets = {
      'item': forms.TextInput(attrs={'class': 'form-control'}),
      'kind': forms.Select(attrs={'class': 'form-control'}),
      'price': forms.NumberInput(attrs={'class': 'form-control'}),
    }

web/views.py
from django.shortcuts import render
from django.views import generic
from .models import Diary, Money
from .forms import DiaryForm, MoneyForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

@method_decorator(login_required, name='dispatch')
class DiaryListView(generic.ListView):
    model = Diary
    ordering = ['-id']
    paginate_by = 3

@method_decorator(login_required, name='dispatch')
class DiaryCreate(CreateView):
    form_class = DiaryForm
    success_url = "/"
    template_name = 'form.html'

@method_decorator(login_required, name='dispatch')
class DiaryUpdate(UpdateView):
    model = Diary
    form_class = DiaryForm
    success_url = "/"
    template_name = 'form.html'

@method_decorator(login_required, name='dispatch')
class DiaryDelete(DeleteView):
    model = Diary
    success_url = "/"
    template_name = 'confirm_delete.html'

@method_decorator(login_required, name='dispatch')
class MoneyListView(generic.ListView):
    model = Money
    ordering = ['-id']
    paginate_by = 3

@method_decorator(login_required, name='dispatch')
class MoneyCreate(CreateView):
    form_class = MoneyForm
    success_url = "/web/money"
    template_name = 'form.html'

@method_decorator(login_required, name='dispatch')
class MoneyUpdate(UpdateView):
    model = Money
    form_class = MoneyForm
    success_url = "/web/money"
    template_name = 'form.html'

@method_decorator(login_required, name='dispatch')
class MoneyDelete(DeleteView):
    model = Money
    success_url = "/web/money"
    template_name = 'confirm_delete.html'

web/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/custom.css">
    <title>數位助理</title>
  </head>
  <body>
    <div class="container">
      {% include "navbar.html" %}
      <div class="content">
        {% block content %}{% endblock %}
      </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  </body>
</html>

web/templates/confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>刪除記錄</h1>

<p>您確定要刪除這筆記錄嗎?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="是的，我要刪除" />
</form>
{% endblock %}

web/templates/form.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  <table class="table table-sm">
  {{ form.as_table }}
  </table>
  <input type="submit" value="送出" class="btn btn-sm btn-primary"/>
</form>
{% endblock %}

web/templates/navbar.html
<!-- Navbar begin //-->
<nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-2">
  <!-- 網站標誌 -->
  <div class="navbar-brand"><i class="far fa-address-card"></i> 數位助理</div>
  <!-- 在小螢幕的設備上顯示可展開/收合導覽選單的按鈕 -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- 導覽列選單內容(可收合) -->
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item"><a href="/" class="nav-link"><i class="fas fa-book"></i> 日記</a></li>
      <li class="nav-item"><a href="/web/diary/create" class="nav-link"><i class="fas fa-edit"></i> 寫日誌</a></li>
      <li class="nav-item"><a href="/web/money" class="nav-link"><i class="fas fa-money-check"></i> 帳本</a></li>
      <li class="nav-item"><a href="/web/money/create" class="nav-link"><i class="fas fa-money-check-alt"></i> 記帳</a></li>
      <li class="nav-item"><a href="/accounts/logout" class="nav-link btn btn-sm btn-primary">{{ user.username }} <i class="fas fa-sign-out-alt"></i> 登出</a></li>
      {% else %}
      <li class="nav-item"><a href="{% url 'login' %}" class="nav-link btn btn-sm btn-primary"><i class="fas fa-sign-in-alt"></i> 登入</a></li>
      {% endif %}
    </ul>
  </div>
</nav>
<!-- Navbar end //-->

web/templates/pagination.html
{% if is_paginated %}
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-sm btn-primary"><i class="fas fa-chevron-circle-left"></i>上一頁</a>
  {% endif %}
  {% for page in page_numbers %}
    {% if page %}
      {% ifequal page page_obj.number %}
        <button class="btn btn-sm btn-primary" disabled>{{ page }}</button>
      {% else %}
        <a href="?page={{ page }}" class="btn btn-sm btn-primary">{{ page }}</a>
      {% endifequal %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-sm btn-primary">下一頁<i class="fas fa-chevron-circle-right"></i></a>
  {% endif %}
{% endif %}

web/templates/web/diary_list.html
{% extends "base.html" %}

{% block content %}
  <h1><i class="fas fa-book"></i> 我的日誌：</h1>
  <table class="table table-sm">
    <tr><td>時間</td><td>項目</td><td>功能</td></tr>
    {% for diary in diary_list %}
    <tr>
      <td>({{diary.time| date:"l"}}){{diary.time}}</td>
      <td><a href="diary/{{diary.id}}/update/">{{diary.memo}}</a></td>
      <td><a href="diary/{{diary.id}}/delete/" class="btn btn-sm btn-danger py-0 px-1"><i class="fas fa-trash-alt"></i> 刪除</a></td>
    </tr>
    {% endfor %}
  </table>
  {% load pagination %}
  {% get_pagination %}
{% endblock %}

{% block content1 %}
<div class="card">
  <div class="card-header h3"><i class="fas fa-book"></i> 我的日誌</div>
  <div class="card-body">
    <table class="table table-sm">
      <thead>
        <tr>
          <th>時間</th>
          <th>項目</th>
          <th>功能</th>
        </tr>
      </thead>
      <tbody>
        {% for diary in diary_list %}
        <tr>
          <td>{{diary.time|date:"Y-m-d H:i"}}</td></td>
          <td><a href="diary/{{diary.id}}/update/">{{diary.memo}}</a></td>
          <td><a href="diary/{{diary.id}}/delete/">刪除</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    {% load pagination %}
    {% get_pagination %}
  </div>
</div>
{% endblock %}

web/templates/web/money_list.html
{% extends "base.html" %}

{% block content %}
  <h1><i class="fas fa-money-check"></i> 我的帳本：</h1>
  <table class="table table-sm">
    <tr>
      <td>時間</td>
      <td>項目</td>
      <td>類別</td>
      <td>金額</td>
      <td>功能</td>
    </tr>
    {% for money in money_list %}
    <tr>
      <td>({{money.time| date:"l"}}){{money.time}}</td>
      <td><a href="money/{{money.id}}/update/">{{money.item}}</a></td>
      <td>{{money.get_kind_display}}</td>
      <td>{{money.price}}</td>
      <td><a href="money/{{money.id}}/delete/" class="btn btn-sm btn-danger py-0 px-1"><i class="fas fa-trash-alt"></i> 刪除</a></td>
    </tr>
    {% endfor %}
  </table>
  {% load pagination %}
  {% get_pagination %}
{% endblock %}